<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemProg.BLL\SemProg.BLL.csproj" />
    <ProjectReference Include="..\SemProg.DAL\SemProg.DAL.csproj" />
  </ItemGroup>

</Project>
