// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemProg.DAL;

#nullable disable

namespace SemProg.DAL.Migrations
{
    [DbContext(typeof(BazaPodatakaKontekst))]
    [Migration("20260320000000_PrevedenaNaSrpski")]
    partial class PrevedenaNaSrpski
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0").HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SemProg.DAL.Modeli.Epizoda", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("KreiraoId").HasColumnType("int");
                b.Property<string>("Opis").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("DatumPremijere").HasColumnType("datetime2");
                b.Property<string>("Naslov").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("KreiraoId");
                b.ToTable("Epizode");
            });

            modelBuilder.Entity("SemProg.DAL.Modeli.Ocena", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Komentar").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("EpizodaId").HasColumnType("int");
                b.Property<DateTime>("OcenjeneNa").HasColumnType("datetime2");
                b.Property<int>("Vrednost").HasColumnType("int");
                b.Property<int>("KorisnikId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("EpizodaId");
                b.HasIndex("KorisnikId");
                b.ToTable("Ocene");
            });

            modelBuilder.Entity("SemProg.DAL.Modeli.Korisnik", b => {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Lozinka").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Uloga").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("KorisnickoIme").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("KorisnickoIme").IsUnique();
                b.ToTable("Korisnici");
            });

            modelBuilder.Entity("SemProg.DAL.Modeli.Epizoda", b => {
                b.HasOne("SemProg.DAL.Modeli.Korisnik", "Kreator").WithMany().HasForeignKey("KreiraoId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Kreator");
            });

            modelBuilder.Entity("SemProg.DAL.Modeli.Ocena", b => {
                b.HasOne("SemProg.DAL.Modeli.Epizoda", "Epizoda").WithMany().HasForeignKey("EpizodaId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("SemProg.DAL.Modeli.Korisnik", "Korisnik").WithMany().HasForeignKey("KorisnikId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Epizoda");
                b.Navigation("Korisnik");
            });
#pragma warning restore 612, 618
        }
    }
}
